version: "3.8"

services:
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_DB: 'pgbd'
      POSTGRES_USER: 'pguser'
      POSTGRES_PASSWORD: '123'
    ports:
      - '5432:5432'
    expose:
      - '5432'

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DB: 'mydb'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: '321'
      MYSQL_ROOT_PASSWORD: '321'
    ports:
      - '3306:3306'
    expose:
      - '3306'